
import json

file_path = r"D:\users\mukul\SharedMukul\Src\forbes\forbes-angular\src\assets\data\Americas_2025.json"

with open(file_path, 'r') as f:
    data = json.load(f)

for company in data:
    if company["COMPANY"] == "Reservoir Media":
        # Rename 'main' to 'overview'
        if "main" in company["DESCRIPTION"]:
            company["DESCRIPTION"]["overview"] = company["DESCRIPTION"].pop("main")
        # Rename 'debt' to 'balancesheet'
        if "debt" in company["DESCRIPTION"]:
            company["DESCRIPTION"]["balancesheet"] = company["DESCRIPTION"].pop("debt")

        # Update overview with ROCE/ROIC
        company["DESCRIPTION"]["overview"] = """Reservoir Media is an independent music company. It operates as both a music publisher, owning a catalog of song copyrights, and a record label. It represents a diverse range of artists and songwriters across many genres. [pos]Reservoir Media has a Return on Invested Capital (ROIC) of 21.33% (GuruFocus, as of June 2025).[/pos] [link to Reservoir Media Investor Relations](https://www.reservoir-media.com/investors/) [link to GuruFocus RSVR ROIC](https://www.gurufocus.com/term/roic/NASDAQ:RSVR)"""

        # Update insider_ownership
        company["DESCRIPTION"]["insider_ownership"] = """[pos]The founder and CEO holds a controlling interest in the company, providing a stable, long-term vision for growing its music assets. Insider ownership varies across sources, from 27.00% (MarketBeat) to 47.54% (Stock Titan).[/pos] [link to MarketBeat RSVR Ownership](https://www.marketbeat.com/stocks/NASDAQ/RSVR/institutional-ownership/) [link to Stock Titan RSVR Ownership](https://stocktitan.net/news/RSVR/reservoir-media-inc-insider-trades-rsvr-stock-titan-47-54-insider-ownership-as-of-july-1-2025.html)"""

        # Update balancesheet with cash levels and debt details
        company["DESCRIPTION"]["balancesheet"] = """The company utilizes debt to finance its primary activity: the acquisition of music catalogs. The predictable, long-term cash flows from these catalogs support the debt service. [pos]As of March 31, 2025, Reservoir Media reported $21.4 million in cash and cash equivalents. Total debt stood at $388.1 million, with a net debt of $366.7 million.[/pos] [link to Reservoir Media Q3 2025 Earnings Release](https://www.reservoir-media.com/news-releases/news-release-details/2025/Reservoir-Media-Inc.-Reports-Third-Quarter-Fiscal-2025-Financial-Results/default.aspx) [link to Simply Wall St RSVR Financials](https://simplywall.st/stocks/us/media/nasdaq-rsvr/reservoir-media/financials)"""

        # Ensure scalability is present and updated
        if "scalability" not in company["DESCRIPTION"]:
            company["DESCRIPTION"]["scalability"] = ""
        company["DESCRIPTION"]["scalability"] = """Scalable through the acquisition of music publishing and recorded music catalogs. Growth is also driven by the global rise of streaming, which increases the value and revenue generated by its existing assets. It scales by finding and acquiring undervalued catalogs."""

        break

with open(file_path, 'w') as f:
    json.dump(data, f, indent=4)

print("Reservoir Media entry updated successfully.")
